import { prisma } from '@/lib/db';

/*
 * Notification types are stored as strings rather than an enum so adding one is
 * a deploy rather than a migration, matching how CommunityReport.reason and
 * CommunityReport.status already work.
 */
export const COMMUNITY_NOTIFICATION_TYPES = [
  'comment_on_post',
  'comment_reply',
  'moderation',
] as const;

export type CommunityNotificationType =
  (typeof COMMUNITY_NOTIFICATION_TYPES)[number];

/*
 * Notifications are generated by the community API, so this list also guards the
 * notification page against rendering a type it does not know how to word.
 */
export const COMMUNITY_NOTIFICATION_LABELS: Record<
  CommunityNotificationType,
  string
> = {
  comment_on_post: 'New comment',
  comment_reply: 'New reply',
  moderation: 'Moderation update',
};

export function isCommunityNotificationType(
  value: unknown
): value is CommunityNotificationType {
  return (
    typeof value === 'string' &&
    COMMUNITY_NOTIFICATION_TYPES.includes(value as CommunityNotificationType)
  );
}

/**
 * Records one notification, skipping anything the recipient should not be told
 * about. Failures are swallowed on purpose: a missing bell badge is not worth
 * failing the comment, upvote or report that triggered it.
 */
export async function createCommunityNotification(input: {
  userId: string;
  type: CommunityNotificationType;
  message: string;
  postId?: string | null;
  commentId?: string | null;
}) {
  /*
   * Nobody is notified about their own activity, and a row is only worth
   * writing when there is somebody left to read it.
   */
  if (!input.userId) {
    return;
  }

  try {
    await prisma.communityNotification.create({
      data: {
        userId: input.userId,
        type: input.type,
        message: input.message.slice(0, 300),
        postId: input.postId ?? null,
        commentId: input.commentId ?? null,
      },
    });
  } catch (error) {
    console.error('Community notification error:', error);
  }
}