function escapePdfText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

export function downloadRecommendedQuestionsPdf(
  company = 'Summit Trails Expeditions'
) {
  const title = 'Wondlo - Recommended Safety Questions';
  const subtitle = `Safety document requested for: ${company}`;
  const generatedOn = `Generated: ${new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })}`;

  const items = [
    'Safety Plan - Can you share your current safety management plan?',
    'Equipment Inspection - Please provide your latest inspection records.',
    'Emergency Response - Do you have an emergency response plan in place?',
    'Insurance - What insurance coverage do you carry for your trips?',
    'Permits - List all permits and authorisations required for your trips.',
    'Guides - What certifications and training do your guides hold?',
    'Weather - How do you respond to adverse weather or route changes?',
    'Travellers - How do you brief travellers on safety before departure?',
  ];

  let stream = 'BT\n/F1 16 Tf\n72 750 Td\n(' + escapePdfText(title) + ') Tj\nET\n';
  stream +=
    'BT\n/F1 11 Tf\n72 724 Td\n(' + escapePdfText(subtitle) + ') Tj\nET\n';
  stream +=
    'BT\n/F1 11 Tf\n72 708 Td\n(' + escapePdfText(generatedOn) + ') Tj\nET\n';
  stream += '0.75 0.72 0.93 RG\n2 w\n72 696 m 540 696 l S\n';

  let y = 670;
  items.forEach((item, index) => {
    stream +=
      'BT\n/F1 11 Tf\n72 ' +
      y +
      ' Td\n(' +
      escapePdfText(`${index + 1}. ${item}`) +
      ') Tj\nET\n';
    y -= 22;
  });

  stream +=
    '0.2 0.2 0.2 RG\n0.8 w\n72 60 m 540 60 l S\n';
  stream +=
    'BT\n/F1 9 Tf\n72 44 Td\n(Generated by Wondlo - Safety as a System) Tj\nET\n';

  const objects: string[] = [];
  const offsets: number[] = [];
  let body = '%PDF-1.4\n';
  const push = (obj: string) => {
    offsets.push(body.length);
    body += obj;
  };

  push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');
  push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n');
  push(
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n'
  );

  const streamData = stream.endsWith('\n') ? stream.slice(0, -1) : stream;
  const streamBytes = new TextEncoder().encode(streamData);
  push(
    '4 0 obj\n<< /Length ' +
      streamBytes.length +
      ' >>\nstream\n' +
      streamData +
      '\nendstream\nendobj\n'
  );
  push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n');

  const xrefStart = body.length;
  body += 'xref\n0 6\n';
  body += '0000000000 65535 f \n';
  for (const off of offsets) {
    body += String(off).padStart(10, '0') + ' 00000 n \n';
  }
  body += 'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n' + xrefStart + '\n%%EOF\n';

  const bytes = new Uint8Array(body.length);
  for (let i = 0; i < body.length; i++) {
    bytes[i] = body.charCodeAt(i) & 0xff;
  }

  const blob = new Blob([bytes], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'wondlo-recommended-questions.pdf';
  link.click();
  URL.revokeObjectURL(url);
}